export const employees = [
  {
    id: "ava-lind",
    name: "Ava Lind",
    role: "Senior Frontend Engineer",
    team: "Engineering",
    location: "Turku",
    workMode: "Hybrid",
    availability: "available",
    capacity: 72,
    skills: ["React", "TypeScript", "Accessibility"],
  },
  {
    id: "leo-niemi",
    name: "Leo Niemi",
    role: "Backend Engineer",
    team: "Engineering",
    location: "Tampere",
    workMode: "Remote",
    availability: "focused",
    capacity: 28,
    skills: ["Python", "Django", "PostgreSQL"],
  },
  {
    id: "mina-koskinen",
    name: "Mina Koskinen",
    role: "Product Designer",
    team: "Design",
    location: "Helsinki",
    workMode: "Hybrid",
    availability: "available",
    capacity: 64,
    skills: ["Product Design", "Research", "Design Systems"],
  },
  {
    id: "noah-virtanen",
    name: "Noah Virtanen",
    role: "Data Engineer",
    team: "Data",
    location: "Espoo",
    workMode: "Remote",
    availability: "available",
    capacity: 55,
    skills: ["Python", "SQL", "Data Pipelines"],
  },
  {
    id: "ella-laine",
    name: "Ella Laine",
    role: "Product Manager",
    team: "Product",
    location: "Turku",
    workMode: "Hybrid",
    availability: "focused",
    capacity: 22,
    skills: ["Discovery", "Roadmapping", "Analytics"],
  },
  {
    id: "oliver-salo",
    name: "Oliver Salo",
    role: "QA Engineer",
    team: "Engineering",
    location: "Oulu",
    workMode: "Remote",
    availability: "available",
    capacity: 81,
    skills: ["Playwright", "Automation", "API Testing"],
  },
  {
    id: "sara-lehto",
    name: "Sara Lehto",
    role: "UX Researcher",
    team: "Design",
    location: "Helsinki",
    workMode: "On-site",
    availability: "away",
    capacity: 0,
    skills: ["Interviews", "Usability", "Synthesis"],
  },
  {
    id: "emil-heikkinen",
    name: "Emil Heikkinen",
    role: "Platform Engineer",
    team: "Engineering",
    location: "Tampere",
    workMode: "Hybrid",
    availability: "focused",
    capacity: 18,
    skills: ["AWS", "Docker", "Observability"],
  },
  {
    id: "lina-makela",
    name: "Lina Mäkelä",
    role: "Data Analyst",
    team: "Data",
    location: "Turku",
    workMode: "Hybrid",
    availability: "available",
    capacity: 68,
    skills: ["SQL", "BI", "Experimentation"],
  },
  {
    id: "anton-ranta",
    name: "Anton Ranta",
    role: "Product Operations",
    team: "Operations",
    location: "Espoo",
    workMode: "Remote",
    availability: "available",
    capacity: 60,
    skills: ["Process", "Automation", "Customer Ops"],
  },
  {
    id: "sofia-kallio",
    name: "Sofia Kallio",
    role: "Frontend Engineer",
    team: "Engineering",
    location: "Helsinki",
    workMode: "Hybrid",
    availability: "focused",
    capacity: 35,
    skills: ["React", "CSS", "Testing"],
  },
  {
    id: "mikael-holm",
    name: "Mikael Holm",
    role: "Service Designer",
    team: "Design",
    location: "Turku",
    workMode: "On-site",
    availability: "available",
    capacity: 76,
    skills: ["Service Design", "Facilitation", "Prototyping"],
  },
];
